OgreOggSound: OgreOggSoundManager Namespace Reference
OgreOggSoundManager Namespace Reference
Classes
struct _sortNearToFar
struct _sortFarToNear
Functions
OgreOggSoundManager ()
~OgreOggSoundManager ()
OgreOggSoundManager * getSingletonPtr (void)
OgreOggSoundManager & getSingleton (void)
bool init (const std::string &deviceName)
Ogre::StringVector getDeviceList ()
StringVector getSoundList ()
void _checkFeatureSupport ()
void _enumDevices ()
OgreOggISound * createSound (const std::string &name, const std::string &file, bool stream, bool loop, bool preBuffer)
void setMasterVolume (ALfloat vol)
ALfloat getMasterVolume ()
OgreOggISound * createSound (SceneManager &scnMgr, const std::string &name, const std::string &file, bool stream, bool loop, bool preBuffer)
OgreOggISound * getSound (const std::string &name)
bool isRecordingAvailable ()
OgreOggSoundRecord * createRecorder ()
bool isEffectSupported (ALint effectID)
void _determineAuxEffectSlots ()
bool _checkEFXSupport ()
bool _checkXRAMSupport ()
void setXRamBuffer (ALsizei numBuffers, ALuint *buffer)
void setXRamBufferMode (ALenum mode)
bool setEFXEffectParameter (const std::string &eName, ALint effectType, ALenum attrib, ALfloat param)
bool setEFXEffectParameter (const std::string &eName, ALint effectType, ALenum attrib, ALfloat *params)
bool setEFXEffectParameter (const std::string &eName, ALint effectType, ALenum attrib, ALint param)
bool setEFXEffectParameter (const std::string &eName, ALint effectType, ALenum attrib, ALint *params)
bool attachEffectToSound (const std::string &sName, ALuint slotID, const Ogre::String &effectName, const Ogre::String &filterName)
bool attachFilterToSound (const std::string &sName, const Ogre::String &filterName)
bool detachEffectFromSound (const std::string &sName, ALuint slotID)
bool detachFilterFromSound (const std::string &sName)
bool _attachEffectToSlot (ALuint slot, ALuint effect)
ALuint _getEFXFilter (const std::string &fName)
ALuint _getEFXEffect (const std::string &eName)
ALuint _getEFXSlot (int slotID)
bool createEFXFilter (const std::string &fName, ALint filterType, ALfloat gain, ALfloat hfGain)
bool createEFXEffect (const std::string &eName, ALint effectType, EAXREVERBPROPERTIES *props)
bool createEFXSlot ()
int getNumberOfSupportedEffectSlots ()
int getNumberOfCreatedEffectSlots ()
bool _setEAXReverbProperties (EFXEAXREVERBPROPERTIES *pEFXEAXReverb, ALuint uiEffect)
bool setEFXSoundProperties (const std::string &sName, Ogre::Real airAbsorption, Ogre::Real roomRolloff, Ogre::Real coneOuterHF)
void setEFXDistanceUnits (Ogre::Real units)
bool hasSound (const std::string &name)
void destroyAllSounds ()
void playSound (const String &sName)
void stopSound (const String &sName)
void pauseSound (const String &sName)
void stopAllSounds ()
void muteAllSounds ()
void unmuteAllSounds ()
void pauseAllSounds ()
void resumeAllPausedSounds ()
void _destroy (OgreOggISound *sound)
void destroySound (const Ogre::String &sName)
void processQueuedSounds ()
void updateBuffers ()
void _release ()
int createSourcePool ()
void _reactivateQueuedSounds ()
bool requestSoundSource (OgreOggISound *sound)
bool releaseSoundSource (OgreOggISound *sound)
ALuint _getSharedBuffer (const String &sName)
bool releaseSharedBuffer (const String &sName, ALuint &buffer)
bool registerSharedBuffer (const String &sName, ALuint &buffer)
void queueDelayedSound (OgreOggISound *sound, DELAYED_ACTION action)
void setDistanceModel (ALenum value)
void setSpeedOfSound (Ogre::Real speed)
void setDopplerFactor (Ogre::Real factor)
void update (Ogre::Real fTime)
Function Documentation
bool OgreOggSoundManager::_attachEffectToSlot (ALuint slot, ALuint effect)
Definition at line 1152 of file ogreoggsoundmanager.cpp.
bool OgreOggSoundManager::_checkEFXSupport ()
Definition at line 777 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::_checkFeatureSupport ()
Definition at line 308 of file ogreoggsoundmanager.cpp.
bool OgreOggSoundManager::_checkXRAMSupport ()
Definition at line 831 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::_destroy (OgreOggISound * sound)
Definition at line 1572 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::_determineAuxEffectSlots ()
Definition at line 630 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::_enumDevices ()
Definition at line 390 of file ogreoggsoundmanager.cpp.
ALuint OgreOggSoundManager::_getEFXEffect (const std::string & eName)
Definition at line 1180 of file ogreoggsoundmanager.cpp.
ALuint OgreOggSoundManager::_getEFXFilter (const std::string & fName)
Definition at line 1168 of file ogreoggsoundmanager.cpp.
ALuint OgreOggSoundManager::_getEFXSlot (int slotID)
Definition at line 1192 of file ogreoggsoundmanager.cpp.
ALuint OgreOggSoundManager::_getSharedBuffer (const String & sName)
Definition at line 2128 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::_reactivateQueuedSounds ()
Definition at line 1904 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::_release ()
Definition at line 1738 of file ogreoggsoundmanager.cpp.
bool OgreOggSoundManager::_setEAXReverbProperties (EFXEAXREVERBPROPERTIES * pEFXEAXReverb, ALuint uiEffect)
Definition at line 1328 of file ogreoggsoundmanager.cpp.
bool OgreOggSoundManager::attachEffectToSound (const std::string & sName, ALuint slotID, const Ogre::String & effectName, const Ogre::String & filterName)
Definition at line 962 of file ogreoggsoundmanager.cpp.
bool OgreOggSoundManager::attachFilterToSound (const std::string & sName, const Ogre::String & filterName)
Definition at line 1017 of file ogreoggsoundmanager.cpp.
bool OgreOggSoundManager::createEFXEffect (const std::string & eName, ALint effectType, EAXREVERBPROPERTIES * props)
Definition at line 1239 of file ogreoggsoundmanager.cpp.
bool OgreOggSoundManager::createEFXFilter (const std::string & fName, ALint filterType, ALfloat gain, ALfloat hfGain)
Definition at line 1200 of file ogreoggsoundmanager.cpp.
bool OgreOggSoundManager::createEFXSlot ()
Definition at line 1283 of file ogreoggsoundmanager.cpp.
OgreOggSoundRecord* OgreOggSoundManager::createRecorder ()
Definition at line 611 of file ogreoggsoundmanager.cpp.
OgreOggISound* OgreOggSoundManager::createSound (SceneManager & scnMgr, const std::string & name, const std::string & file, bool stream, bool loop, bool preBuffer)
Definition at line 562 of file ogreoggsoundmanager.cpp.
OgreOggISound* OgreOggSoundManager::createSound (const std::string & name, const std::string & file, bool stream, bool loop, bool preBuffer)
Definition at line 396 of file ogreoggsoundmanager.cpp.
int OgreOggSoundManager::createSourcePool ()
Definition at line 1826 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::destroyAllSounds ()
Definition at line 1450 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::destroySound (const Ogre::String & sName)
Definition at line 1607 of file ogreoggsoundmanager.cpp.
bool OgreOggSoundManager::detachEffectFromSound (const std::string & sName, ALuint slotID)
Definition at line 1064 of file ogreoggsoundmanager.cpp.
bool OgreOggSoundManager::detachFilterFromSound (const std::string & sName)
Definition at line 1114 of file ogreoggsoundmanager.cpp.
Ogre::StringVector OgreOggSoundManager::getDeviceList ()
Definition at line 248 of file ogreoggsoundmanager.cpp.
Referenced by init().
ALfloat OgreOggSoundManager::getMasterVolume ()
Definition at line 554 of file ogreoggsoundmanager.cpp.
int OgreOggSoundManager::getNumberOfCreatedEffectSlots ()
Definition at line 1320 of file ogreoggsoundmanager.cpp.
int OgreOggSoundManager::getNumberOfSupportedEffectSlots ()
Definition at line 1309 of file ogreoggsoundmanager.cpp.
OgreOggSoundManager& OgreOggSoundManager::getSingleton (void)
Definition at line 135 of file ogreoggsoundmanager.cpp.
Referenced by dllStartPlugin(), dllStopPlugin(), init(), OgreOggSound::OgreOggSoundPlugin::install(), OgreOggSound::OgreOggSoundManager::threadUpdate(), and OgreOggSound::OgreOggSoundPlugin::uninstall().
OgreOggSoundManager* OgreOggSoundManager::getSingletonPtr (void)
Definition at line 129 of file ogreoggsoundmanager.cpp.
OgreOggISound* OgreOggSoundManager::getSound (const std::string & name)
Definition at line 591 of file ogreoggsoundmanager.cpp.
StringVector OgreOggSoundManager::getSoundList ()
Definition at line 300 of file ogreoggsoundmanager.cpp.
bool OgreOggSoundManager::hasSound (const std::string & name)
Definition at line 1439 of file ogreoggsoundmanager.cpp.
bool OgreOggSoundManager::init (const std::string & deviceName)
Definition at line 141 of file ogreoggsoundmanager.cpp.
References getDeviceList(), and getSingleton().
bool OgreOggSoundManager::isEffectSupported (ALint effectID)
Definition at line 620 of file ogreoggsoundmanager.cpp.
bool OgreOggSoundManager::isRecordingAvailable ()
Definition at line 604 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::muteAllSounds ()
Definition at line 1526 of file ogreoggsoundmanager.cpp.
OgreOggSoundManager::OgreOggSoundManager ()
Definition at line 40 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::pauseAllSounds ()
Definition at line 1537 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::pauseSound (const String & sName)
Definition at line 1498 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::playSound (const String & sName)
Definition at line 1472 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::processQueuedSounds ()
Definition at line 1624 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::queueDelayedSound (OgreOggISound * sound, DELAYED_ACTION action)
Definition at line 2194 of file ogreoggsoundmanager.cpp.
bool OgreOggSoundManager::registerSharedBuffer (const String & sName, ALuint & buffer)
Definition at line 2172 of file ogreoggsoundmanager.cpp.
bool OgreOggSoundManager::releaseSharedBuffer (const String & sName, ALuint & buffer)
Definition at line 2142 of file ogreoggsoundmanager.cpp.
bool OgreOggSoundManager::releaseSoundSource (OgreOggISound * sound)
Definition at line 2086 of file ogreoggsoundmanager.cpp.
bool OgreOggSoundManager::requestSoundSource (OgreOggISound * sound)
Definition at line 1936 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::resumeAllPausedSounds ()
Definition at line 1558 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::setDistanceModel (ALenum value)
Definition at line 2238 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::setDopplerFactor (Ogre::Real factor)
Definition at line 2248 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::setEFXDistanceUnits (Ogre::Real units)
Definition at line 1431 of file ogreoggsoundmanager.cpp.
bool OgreOggSoundManager::setEFXEffectParameter (const std::string & eName, ALint effectType, ALenum attrib, ALint * params)
Definition at line 940 of file ogreoggsoundmanager.cpp.
bool OgreOggSoundManager::setEFXEffectParameter (const std::string & eName, ALint effectType, ALenum attrib, ALint param)
Definition at line 918 of file ogreoggsoundmanager.cpp.
bool OgreOggSoundManager::setEFXEffectParameter (const std::string & eName, ALint effectType, ALenum attrib, ALfloat * params)
Definition at line 896 of file ogreoggsoundmanager.cpp.
bool OgreOggSoundManager::setEFXEffectParameter (const std::string & eName, ALint effectType, ALenum attrib, ALfloat param)
Definition at line 874 of file ogreoggsoundmanager.cpp.
bool OgreOggSoundManager::setEFXSoundProperties (const std::string & sName, Ogre::Real airAbsorption, Ogre::Real roomRolloff, Ogre::Real coneOuterHF)
Definition at line 1390 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::setMasterVolume (ALfloat vol)
Definition at line 545 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::setSpeedOfSound (Ogre::Real speed)
Definition at line 2243 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::setXRamBuffer (ALsizei numBuffers, ALuint * buffer)
Definition at line 860 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::setXRamBufferMode (ALenum mode)
Definition at line 866 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::stopAllSounds ()
Definition at line 1512 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::stopSound (const String & sName)
Definition at line 1484 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::unmuteAllSounds ()
Definition at line 1532 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::update (Ogre::Real fTime)
Definition at line 2253 of file ogreoggsoundmanager.cpp.
void OgreOggSoundManager::updateBuffers ()
Definition at line 1715 of file ogreoggsoundmanager.cpp.
OgreOggSoundManager::~OgreOggSoundManager ()
Definition at line 106 of file ogreoggsoundmanager.cpp.