OgreOggSound: OgreOggSound::OgreOggListener Class Reference
OgreOggSound::OgreOggListener Class Reference
Listener object (Users ears)
#include <OgreOggListener.h>
Public Member Functions
OgreOggListener (Ogre::SceneManager *scnMgr=NULL)
void setPosition (ALfloat x, ALfloat y, ALfloat z)
void setPosition (const Ogre::Vector3 &pos)
Ogre::Vector3 getPosition () const
void setOrientation (ALfloat x, ALfloat y, ALfloat z, ALfloat upx, ALfloat upy, ALfloat upz)
void setOrientation (const Ogre::Quaternion &q)
Ogre::Vector3 getOrientation () const
void setVelocity (float velx, float vely, float velz)
void setVelocity (const Ogre::Vector3 &vel)
void update ()
virtual const Ogre::String & getMovableType (void) const
virtual const Ogre::AxisAlignedBox & getBoundingBox (void) const
virtual float getBoundingRadius (void) const
virtual void _updateRenderQueue (Ogre::RenderQueue *queue)
virtual void visitRenderables (Ogre::Renderable::Visitor *visitor, bool debugRenderables)
virtual void _notifyAttached (Ogre::Node *node)
virtual void _updateRenderQueue (Ogre::RenderQueue *queue, Ogre::Camera *camera, const Ogre::Camera *lodCamera)
Ogre::SceneManager * getSceneManager ()
Public Member Functions inherited from Ogre::MovableObject
MovableObject ()
MovableObject (const String &name)
virtual ~MovableObject ()
MovableObjectFactory * _getCreator (void) const
LightList * _getLightList ()
SceneManager * _getManager (void) const
virtual const Matrix4 & _getParentNodeFullTransform (void) const
virtual void _notifyAttached (Node *parent, bool isTagPoint=false)
virtual void _notifyCreator (MovableObjectFactory *fact)
virtual void _notifyCurrentCamera (Camera *cam)
virtual void _notifyManager (SceneManager *man)
virtual void _notifyMoved (void)
virtual void _releaseManualHardwareResources ()
virtual void _restoreManualHardwareResources ()
void addQueryFlags (uint32 flags)
void addVisibilityFlags (uint32 flags)
virtual AnimableValuePtr createAnimableValue (const String &valueName)
void detachFromParent (void)
const StringVector & getAnimableValueNames (void) const
bool getCastShadows (void) const
const AxisAlignedBox & getDarkCapBounds (const Light &light, Real dirLightExtrusionDist) const
EdgeData * getEdgeList (void)
const AxisAlignedBox & getLightCapBounds (void) const
uint32 getLightMask () const
Listener * getListener (void) const
const String & getName (void) const
Node * getParentNode (void) const
SceneNode * getParentSceneNode (void) const
Real getPointExtrusionDistance (const Light *l) const
uint32 getQueryFlags (void) const
bool getReceivesShadows ()
Real getRenderingDistance (void) const
Real getRenderingMinPixelSize () const
uint8 getRenderQueueGroup (void) const
ShadowRenderableListIterator getShadowVolumeRenderableIterator (ShadowTechnique shadowTechnique, const Light *light, HardwareIndexBufferSharedPtr *indexBuffer, size_t *indexBufferUsedSize, bool extrudeVertices, Real extrusionDist, unsigned long flags=0)
virtual uint32 getTypeFlags (void) const
const Any & getUserAny (void) const
UserObjectBindings & getUserObjectBindings ()
const UserObjectBindings & getUserObjectBindings () const
uint32 getVisibilityFlags (void) const
bool getVisible (void) const
virtual const AxisAlignedBox & getWorldBoundingBox (bool derive=false) const
virtual const Sphere & getWorldBoundingSphere (bool derive=false) const
bool hasEdgeList (void)
bool isAttached (void) const
bool isDebugDisplayEnabled (void) const
virtual bool isInScene (void) const
bool isParentTagPoint () const
virtual bool isVisible (void) const
const LightList & queryLights (void) const
void removeQueryFlags (uint32 flags)
void removeVisibilityFlags (uint32 flags)
void setCastShadows (bool enabled)
void setDebugDisplayEnabled (bool enabled)
void setLightMask (uint32 lightMask)
void setListener (Listener *listener)
void setQueryFlags (uint32 flags)
void setRenderingDistance (Real dist)
void setRenderingMinPixelSize (Real pixelSize)
virtual void setRenderQueueGroup (uint8 queueID)
virtual void setRenderQueueGroupAndPriority (uint8 queueID, ushort priority)
void setUserAny (const Any &anything)
void setVisibilityFlags (uint32 flags)
void setVisible (bool visible)
Public Member Functions inherited from Ogre::ShadowCaster
virtual ~ShadowCaster ()
Public Member Functions inherited from Ogre::AnimableObject
AnimableObject ()
virtual ~AnimableObject ()
const StringVector & getAnimableValueNames (void) const
Private Attributes
Ogre::Vector3 mPosition
Ogre::Vector3 mVelocity
float mOrientation [6]
bool mLocalTransformDirty
Ogre::SceneManager * mSceneMgr
Additional Inherited Members
Public Types inherited from Ogre::MovableObject
typedef vector< ShadowRenderable * >::type ShadowRenderableList
typedef VectorIterator< ShadowRenderableList > ShadowRenderableListIterator
Public Types inherited from Ogre::ShadowCaster
typedef vector< ShadowRenderable * >::type ShadowRenderableList
typedef VectorIterator< ShadowRenderableList > ShadowRenderableListIterator
Static Public Member Functions inherited from Ogre::MovableObject
static void clearShadowRenderableList (ShadowRenderableList &shadowRenderables)
static void extrudeVertices (const HardwareVertexBufferSharedPtr &vertexBuffer, size_t originalVertexCount, const Vector4 &lightPos, Real extrudeDist)
static uint32 getDefaultQueryFlags ()
static uint32 getDefaultVisibilityFlags ()
static void setDefaultQueryFlags (uint32 flags)
static void setDefaultVisibilityFlags (uint32 flags)
Static Public Member Functions inherited from Ogre::ShadowCaster
static void clearShadowRenderableList (ShadowRenderableList &shadowRenderables)
static void extrudeVertices (const HardwareVertexBufferSharedPtr &vertexBuffer, size_t originalVertexCount, const Vector4 &lightPos, Real extrudeDist)
Detailed Description
Listener object (Users ears)
Handles properties associated with the listener.
Constructor & Destructor Documentation
OgreOggSound::OgreOggListener::OgreOggListener (Ogre::SceneManager * scnMgr = NULL)
Constructor
Remarks
Creates a listener object to act as the ears of the user.
References _notifyAttached(), _notifyMoved(), _updateRenderQueue(), getBoundingBox(), getBoundingRadius(), getMovableType(), getOrientation(), getPosition(), OGRE_VERSION_MAJOR, OGRE_VERSION_MINOR, setOrientation(), setPosition(), and visitRenderables().
Member Function Documentation
virtual void OgreOggSound::OgreOggListener::_notifyAttached (Ogre::Node * node) virtual
Attach callback
Remarks
Overridden function from MovableObject.
virtual void OgreOggSound::OgreOggListener::_updateRenderQueue (Ogre::RenderQueue * queue) virtual
Updates the RenderQueue for this object
Remarks
Overridden function from MovableObject.
Implements Ogre::MovableObject.
virtual void OgreOggSound::OgreOggListener::_updateRenderQueue (Ogre::RenderQueue * queue, Ogre::Camera * camera, const Ogre::Camera * lodCamera) virtual
do nothing but need for derived from MovableObject
virtual const Ogre::AxisAlignedBox& OgreOggSound::OgreOggListener::getBoundingBox (void) const virtual
Gets the bounding box of this object.
Remarks
Overridden function from MovableObject, provides a bounding box for this object.
Implements Ogre::MovableObject.
virtual float OgreOggSound::OgreOggListener::getBoundingRadius (void) const virtual
Gets the bounding radius of this object.
Remarks
Overridden function from MovableObject, provides the bounding radius for this object.
Implements Ogre::MovableObject.
virtual const Ogre::String& OgreOggSound::OgreOggListener::getMovableType (void) const virtual
Gets the movable type string for this object.
Remarks
Overridden function from MovableObject, returns a Sound object string for identification.
Implements Ogre::MovableObject.
Ogre::Vector3 OgreOggSound::OgreOggListener::getOrientation () const
Gets the orientation of the listener.
Ogre::Vector3 OgreOggSound::OgreOggListener::getPosition () const
Gets the position of the listener.
Ogre::SceneManager* OgreOggSound::OgreOggListener::getSceneManager ()
Returns scenemanager which created this listener.
void OgreOggSound::OgreOggListener::setOrientation (ALfloat x, ALfloat y, ALfloat z, ALfloat upx, ALfloat upy, ALfloat upz)
Sets the orientation of the listener.
Remarks
Sets the 3D orientation of the listener. This is a manual method, if attached to a SceneNode this will automatically be handled for you.
Parameters
x/y/z direction.
upx/upy/upz up.
void OgreOggSound::OgreOggListener::setOrientation (const Ogre::Quaternion & q)
Sets the orientation of the listener.
Remarks
Sets the 3D orientation of the listener. This is a manual method, if attached to a SceneNode this will automatically be handled for you.
Parameters
q Orientation quaternion.
void OgreOggSound::OgreOggListener::setPosition (ALfloat x, ALfloat y, ALfloat z)
Sets the position of the listener.
Remarks
Sets the 3D position of the listener. This is a manual method, if attached to a SceneNode this will automatically be handled for you.
Parameters
x/y/z position.
void OgreOggSound::OgreOggListener::setPosition (const Ogre::Vector3 & pos)
Sets the position of the listener.
Remarks
Sets the 3D position of the listener. This is a manual method, if attached to a SceneNode this will automatically be handled for you.
Parameters
pos Vector position.
void OgreOggSound::OgreOggListener::setVelocity (float velx, float vely, float velz)
Sets sounds velocity.
Parameters
vel 3D x/y/z velocity
void OgreOggSound::OgreOggListener::setVelocity (const Ogre::Vector3 & vel)
Sets sounds velocity.
Parameters
vel 3D vector velocity
void OgreOggSound::OgreOggListener::update ()
Updates the listener.
Remarks
Handles positional updates to the listener either automatically through the SceneGraph attachment or manually using the provided functions.
virtual void OgreOggSound::OgreOggListener::visitRenderables (Ogre::Renderable::Visitor * visitor, bool debugRenderables) virtual
Renderable callback
Remarks
Overridden function from MovableObject.
Implements Ogre::MovableObject.
Member Data Documentation
bool OgreOggSound::OgreOggListener::mLocalTransformDirty private
float OgreOggSound::OgreOggListener::mOrientation[6] private
Ogre::Vector3 OgreOggSound::OgreOggListener::mPosition private
Positional variables
Ogre::SceneManager* OgreOggSound::OgreOggListener::mSceneMgr private
Ogre::Vector3 OgreOggSound::OgreOggListener::mVelocity private
The documentation for this class was generated from the following file:
OgreOggListener.h