# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/daddy/Documents/OgreOggSound_new

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/daddy/Documents/OgreOggSound_new

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daddy/Documents/OgreOggSound_new/CMakeFiles /home/daddy/Documents/OgreOggSound_new/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daddy/Documents/OgreOggSound_new/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ogreoggsound

# Build rule for target.
ogreoggsound: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ogreoggsound
.PHONY : ogreoggsound

# fast build rule for target.
ogreoggsound/fast:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/build
.PHONY : ogreoggsound/fast

src/OgreOggISound.o: src/OgreOggISound.cpp.o
.PHONY : src/OgreOggISound.o

# target to build an object file
src/OgreOggISound.cpp.o:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggISound.cpp.o
.PHONY : src/OgreOggISound.cpp.o

src/OgreOggISound.i: src/OgreOggISound.cpp.i
.PHONY : src/OgreOggISound.i

# target to preprocess a source file
src/OgreOggISound.cpp.i:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggISound.cpp.i
.PHONY : src/OgreOggISound.cpp.i

src/OgreOggISound.s: src/OgreOggISound.cpp.s
.PHONY : src/OgreOggISound.s

# target to generate assembly for a file
src/OgreOggISound.cpp.s:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggISound.cpp.s
.PHONY : src/OgreOggISound.cpp.s

src/OgreOggListener.o: src/OgreOggListener.cpp.o
.PHONY : src/OgreOggListener.o

# target to build an object file
src/OgreOggListener.cpp.o:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggListener.cpp.o
.PHONY : src/OgreOggListener.cpp.o

src/OgreOggListener.i: src/OgreOggListener.cpp.i
.PHONY : src/OgreOggListener.i

# target to preprocess a source file
src/OgreOggListener.cpp.i:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggListener.cpp.i
.PHONY : src/OgreOggListener.cpp.i

src/OgreOggListener.s: src/OgreOggListener.cpp.s
.PHONY : src/OgreOggListener.s

# target to generate assembly for a file
src/OgreOggListener.cpp.s:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggListener.cpp.s
.PHONY : src/OgreOggListener.cpp.s

src/OgreOggSoundFactory.o: src/OgreOggSoundFactory.cpp.o
.PHONY : src/OgreOggSoundFactory.o

# target to build an object file
src/OgreOggSoundFactory.cpp.o:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggSoundFactory.cpp.o
.PHONY : src/OgreOggSoundFactory.cpp.o

src/OgreOggSoundFactory.i: src/OgreOggSoundFactory.cpp.i
.PHONY : src/OgreOggSoundFactory.i

# target to preprocess a source file
src/OgreOggSoundFactory.cpp.i:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggSoundFactory.cpp.i
.PHONY : src/OgreOggSoundFactory.cpp.i

src/OgreOggSoundFactory.s: src/OgreOggSoundFactory.cpp.s
.PHONY : src/OgreOggSoundFactory.s

# target to generate assembly for a file
src/OgreOggSoundFactory.cpp.s:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggSoundFactory.cpp.s
.PHONY : src/OgreOggSoundFactory.cpp.s

src/OgreOggSoundPlugin.o: src/OgreOggSoundPlugin.cpp.o
.PHONY : src/OgreOggSoundPlugin.o

# target to build an object file
src/OgreOggSoundPlugin.cpp.o:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggSoundPlugin.cpp.o
.PHONY : src/OgreOggSoundPlugin.cpp.o

src/OgreOggSoundPlugin.i: src/OgreOggSoundPlugin.cpp.i
.PHONY : src/OgreOggSoundPlugin.i

# target to preprocess a source file
src/OgreOggSoundPlugin.cpp.i:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggSoundPlugin.cpp.i
.PHONY : src/OgreOggSoundPlugin.cpp.i

src/OgreOggSoundPlugin.s: src/OgreOggSoundPlugin.cpp.s
.PHONY : src/OgreOggSoundPlugin.s

# target to generate assembly for a file
src/OgreOggSoundPlugin.cpp.s:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggSoundPlugin.cpp.s
.PHONY : src/OgreOggSoundPlugin.cpp.s

src/OgreOggSoundPluginDllStart.o: src/OgreOggSoundPluginDllStart.cpp.o
.PHONY : src/OgreOggSoundPluginDllStart.o

# target to build an object file
src/OgreOggSoundPluginDllStart.cpp.o:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggSoundPluginDllStart.cpp.o
.PHONY : src/OgreOggSoundPluginDllStart.cpp.o

src/OgreOggSoundPluginDllStart.i: src/OgreOggSoundPluginDllStart.cpp.i
.PHONY : src/OgreOggSoundPluginDllStart.i

# target to preprocess a source file
src/OgreOggSoundPluginDllStart.cpp.i:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggSoundPluginDllStart.cpp.i
.PHONY : src/OgreOggSoundPluginDllStart.cpp.i

src/OgreOggSoundPluginDllStart.s: src/OgreOggSoundPluginDllStart.cpp.s
.PHONY : src/OgreOggSoundPluginDllStart.s

# target to generate assembly for a file
src/OgreOggSoundPluginDllStart.cpp.s:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggSoundPluginDllStart.cpp.s
.PHONY : src/OgreOggSoundPluginDllStart.cpp.s

src/OgreOggSoundRecord.o: src/OgreOggSoundRecord.cpp.o
.PHONY : src/OgreOggSoundRecord.o

# target to build an object file
src/OgreOggSoundRecord.cpp.o:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggSoundRecord.cpp.o
.PHONY : src/OgreOggSoundRecord.cpp.o

src/OgreOggSoundRecord.i: src/OgreOggSoundRecord.cpp.i
.PHONY : src/OgreOggSoundRecord.i

# target to preprocess a source file
src/OgreOggSoundRecord.cpp.i:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggSoundRecord.cpp.i
.PHONY : src/OgreOggSoundRecord.cpp.i

src/OgreOggSoundRecord.s: src/OgreOggSoundRecord.cpp.s
.PHONY : src/OgreOggSoundRecord.s

# target to generate assembly for a file
src/OgreOggSoundRecord.cpp.s:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggSoundRecord.cpp.s
.PHONY : src/OgreOggSoundRecord.cpp.s

src/OgreOggStaticSound.o: src/OgreOggStaticSound.cpp.o
.PHONY : src/OgreOggStaticSound.o

# target to build an object file
src/OgreOggStaticSound.cpp.o:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggStaticSound.cpp.o
.PHONY : src/OgreOggStaticSound.cpp.o

src/OgreOggStaticSound.i: src/OgreOggStaticSound.cpp.i
.PHONY : src/OgreOggStaticSound.i

# target to preprocess a source file
src/OgreOggStaticSound.cpp.i:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggStaticSound.cpp.i
.PHONY : src/OgreOggStaticSound.cpp.i

src/OgreOggStaticSound.s: src/OgreOggStaticSound.cpp.s
.PHONY : src/OgreOggStaticSound.s

# target to generate assembly for a file
src/OgreOggStaticSound.cpp.s:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggStaticSound.cpp.s
.PHONY : src/OgreOggStaticSound.cpp.s

src/OgreOggStaticWavSound.o: src/OgreOggStaticWavSound.cpp.o
.PHONY : src/OgreOggStaticWavSound.o

# target to build an object file
src/OgreOggStaticWavSound.cpp.o:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggStaticWavSound.cpp.o
.PHONY : src/OgreOggStaticWavSound.cpp.o

src/OgreOggStaticWavSound.i: src/OgreOggStaticWavSound.cpp.i
.PHONY : src/OgreOggStaticWavSound.i

# target to preprocess a source file
src/OgreOggStaticWavSound.cpp.i:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggStaticWavSound.cpp.i
.PHONY : src/OgreOggStaticWavSound.cpp.i

src/OgreOggStaticWavSound.s: src/OgreOggStaticWavSound.cpp.s
.PHONY : src/OgreOggStaticWavSound.s

# target to generate assembly for a file
src/OgreOggStaticWavSound.cpp.s:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggStaticWavSound.cpp.s
.PHONY : src/OgreOggStaticWavSound.cpp.s

src/OgreOggStreamWavSound.o: src/OgreOggStreamWavSound.cpp.o
.PHONY : src/OgreOggStreamWavSound.o

# target to build an object file
src/OgreOggStreamWavSound.cpp.o:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggStreamWavSound.cpp.o
.PHONY : src/OgreOggStreamWavSound.cpp.o

src/OgreOggStreamWavSound.i: src/OgreOggStreamWavSound.cpp.i
.PHONY : src/OgreOggStreamWavSound.i

# target to preprocess a source file
src/OgreOggStreamWavSound.cpp.i:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggStreamWavSound.cpp.i
.PHONY : src/OgreOggStreamWavSound.cpp.i

src/OgreOggStreamWavSound.s: src/OgreOggStreamWavSound.cpp.s
.PHONY : src/OgreOggStreamWavSound.s

# target to generate assembly for a file
src/OgreOggStreamWavSound.cpp.s:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/OgreOggStreamWavSound.cpp.s
.PHONY : src/OgreOggStreamWavSound.cpp.s

src/ogreoggsoundmanager.o: src/ogreoggsoundmanager.cpp.o
.PHONY : src/ogreoggsoundmanager.o

# target to build an object file
src/ogreoggsoundmanager.cpp.o:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/ogreoggsoundmanager.cpp.o
.PHONY : src/ogreoggsoundmanager.cpp.o

src/ogreoggsoundmanager.i: src/ogreoggsoundmanager.cpp.i
.PHONY : src/ogreoggsoundmanager.i

# target to preprocess a source file
src/ogreoggsoundmanager.cpp.i:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/ogreoggsoundmanager.cpp.i
.PHONY : src/ogreoggsoundmanager.cpp.i

src/ogreoggsoundmanager.s: src/ogreoggsoundmanager.cpp.s
.PHONY : src/ogreoggsoundmanager.s

# target to generate assembly for a file
src/ogreoggsoundmanager.cpp.s:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/ogreoggsoundmanager.cpp.s
.PHONY : src/ogreoggsoundmanager.cpp.s

src/ogreoggstreamsound.o: src/ogreoggstreamsound.cpp.o
.PHONY : src/ogreoggstreamsound.o

# target to build an object file
src/ogreoggstreamsound.cpp.o:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/ogreoggstreamsound.cpp.o
.PHONY : src/ogreoggstreamsound.cpp.o

src/ogreoggstreamsound.i: src/ogreoggstreamsound.cpp.i
.PHONY : src/ogreoggstreamsound.i

# target to preprocess a source file
src/ogreoggstreamsound.cpp.i:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/ogreoggstreamsound.cpp.i
.PHONY : src/ogreoggstreamsound.cpp.i

src/ogreoggstreamsound.s: src/ogreoggstreamsound.cpp.s
.PHONY : src/ogreoggstreamsound.s

# target to generate assembly for a file
src/ogreoggstreamsound.cpp.s:
	$(MAKE) -f CMakeFiles/ogreoggsound.dir/build.make CMakeFiles/ogreoggsound.dir/src/ogreoggstreamsound.cpp.s
.PHONY : src/ogreoggstreamsound.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... ogreoggsound"
	@echo "... rebuild_cache"
	@echo "... src/OgreOggISound.o"
	@echo "... src/OgreOggISound.i"
	@echo "... src/OgreOggISound.s"
	@echo "... src/OgreOggListener.o"
	@echo "... src/OgreOggListener.i"
	@echo "... src/OgreOggListener.s"
	@echo "... src/OgreOggSoundFactory.o"
	@echo "... src/OgreOggSoundFactory.i"
	@echo "... src/OgreOggSoundFactory.s"
	@echo "... src/OgreOggSoundPlugin.o"
	@echo "... src/OgreOggSoundPlugin.i"
	@echo "... src/OgreOggSoundPlugin.s"
	@echo "... src/OgreOggSoundPluginDllStart.o"
	@echo "... src/OgreOggSoundPluginDllStart.i"
	@echo "... src/OgreOggSoundPluginDllStart.s"
	@echo "... src/OgreOggSoundRecord.o"
	@echo "... src/OgreOggSoundRecord.i"
	@echo "... src/OgreOggSoundRecord.s"
	@echo "... src/OgreOggStaticSound.o"
	@echo "... src/OgreOggStaticSound.i"
	@echo "... src/OgreOggStaticSound.s"
	@echo "... src/OgreOggStaticWavSound.o"
	@echo "... src/OgreOggStaticWavSound.i"
	@echo "... src/OgreOggStaticWavSound.s"
	@echo "... src/OgreOggStreamWavSound.o"
	@echo "... src/OgreOggStreamWavSound.i"
	@echo "... src/OgreOggStreamWavSound.s"
	@echo "... src/ogreoggsoundmanager.o"
	@echo "... src/ogreoggsoundmanager.i"
	@echo "... src/ogreoggsoundmanager.s"
	@echo "... src/ogreoggstreamsound.o"
	@echo "... src/ogreoggstreamsound.i"
	@echo "... src/ogreoggstreamsound.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

