OgreOggSound: OgreOggSound::OgreOggSoundManager Class Reference
OgreOggSound::OgreOggSoundManager Class Reference
#include <OgreOggSoundManager.h>
Public Member Functions
OgreOggSoundManager ()
~OgreOggSoundManager ()
bool init (const std::string &deviceName="")
int createSourcePool ()
void setMasterVolume (ALfloat vol)
ALfloat getMasterVolume ()
OgreOggISound * createSound (const std::string &name, const std::string &file, bool stream=false, bool loop=false, bool preBuffer=false)
OgreOggISound * createSound (Ogre::SceneManager &scnMgr, const std::string &name, const std::string &file, bool stream=false, bool loop=false, bool preBuffer=false)
OgreOggISound * getSound (const std::string &name)
Ogre::StringVector getSoundList ()
bool hasSound (const std::string &name)
void playSound (const Ogre::String &sName)
void pauseSound (const Ogre::String &sName)
void stopSound (const Ogre::String &sName)
void stopAllSounds ()
void pauseAllSounds ()
void muteAllSounds ()
void unmuteAllSounds ()
void resumeAllPausedSounds ()
void destroyAllSounds ()
bool hasXRamSupport ()
bool hasEFXSupport ()
bool hasEAXSupport ()
void destroySound (const std::string &name="")
void updateBuffers ()
bool requestSoundSource (OgreOggISound *sound=0)
bool releaseSoundSource (OgreOggISound *sound=0)
void setDistanceModel (ALenum value)
void setDopplerFactor (Ogre::Real factor=1.f)
void setSpeedOfSound (Ogre::Real speed=363.f)
Ogre::StringVector getDeviceList ()
OgreOggListener * getListener ()
int getNumSources ()
void processQueuedSounds (void)
void update (Ogre::Real fTime=0.f)
void setXRamBuffer (ALsizei numBuffers, ALuint *buffers)
void setXRamBufferMode (ALenum mode)
void setEFXDistanceUnits (Ogre::Real unit=3.3f)
bool createEFXFilter (const std::string &eName, ALint type, ALfloat gain=1.0, ALfloat hfGain=1.0)
bool createEFXEffect (const std::string &eName, ALint type, EAXREVERBPROPERTIES *props=0)
bool setEFXSoundProperties (const std::string &eName, Ogre::Real airAbsorption=0.f, Ogre::Real roomRolloff=0.f, Ogre::Real coneOuterHF=0.f)
bool setEFXEffectParameter (const std::string &eName, ALint effectType, ALenum attrib, ALfloat param)
bool setEFXEffectParameter (const std::string &eName, ALint type, ALenum attrib, ALfloat *params=0)
bool setEFXEffectParameter (const std::string &eName, ALint type, ALenum attrib, ALint param)
bool setEFXEffectParameter (const std::string &eName, ALint type, ALenum attrib, ALint *params=0)
int getNumberOfSupportedEffectSlots ()
int getNumberOfCreatedEffectSlots ()
bool createEFXSlot ()
bool attachEffectToSound (const std::string &sName, ALuint slot, const Ogre::String &effect="", const Ogre::String &filter="")
bool attachFilterToSound (const std::string &sName, const Ogre::String &filter="")
bool detachEffectFromSound (const std::string &sName, ALuint slotID)
bool detachFilterFromSound (const std::string &sName)
bool isEffectSupported (ALint effectID)
OgreOggSoundRecord * getRecorder ()
bool isRecordingAvailable ()
OgreOggSoundRecord * createRecorder ()
bool releaseSharedBuffer (const Ogre::String &sName, ALuint &buffer)
bool registerSharedBuffer (const Ogre::String &sName, ALuint &buffer)
void queueDelayedSound (OgreOggISound *sound=0, DELAYED_ACTION action=DA_PLAY)
Static Public Member Functions
static OgreOggSoundManager & getSingleton (void)
static OgreOggSoundManager * getSingletonPtr (void)
static void threadUpdate ()
Public Attributes
boost::recursive_mutex mMutex
static::boost::thread * mUpdateThread
Static Public Attributes
static bool mShuttingDown
Protected Member Functions
void _destroySound (OgreOggISound *sound=0)
void _removeFromLists (OgreOggISound *sound=0)
Private Types
typedef ALboolean(__cdecl * LPEAXSETBUFFERMODE)(ALsizei n, ALuint *buffers, ALint value)
typedef ALenum(__cdecl * LPEAXGETBUFFERMODE)(ALuint buffer, ALint *value)
Private Member Functions
ALuint _getSharedBuffer (const Ogre::String &sName)
void _release ()
void _checkFeatureSupport ()
bool _checkEFXSupport ()
bool _checkXRAMSupport ()
void _determineAuxEffectSlots ()
ALuint _getEFXFilter (const std::string &fName)
ALuint _getEFXEffect (const std::string &eName)
ALuint _getEFXSlot (int slotID=0)
bool _setEAXReverbProperties (EFXEAXREVERBPROPERTIES *pEFXEAXReverb, ALuint uiEffect)
bool _attachEffectToSlot (ALuint slot, ALuint effect)
void _reactivateQueuedSounds ()
void _enumDevices ()
Private Attributes
ALCdevice * mDevice
ALCcontext * mContext
ALfloat mOrigVolume
SoundMap mSoundMap
ActiveList mActiveSounds
FileOpenList mQueuedSounds
ActiveList mPlayQueue
ActiveList mPauseQueue
ActiveList mStopQueue
ActiveList mPausedSounds
ActiveList mSoundsToReactivate
SourceList mSourcePool
FeatureList mEFXSupportList
SharedBufferList mSharedBuffers
ALCchar * mDeviceStrings
int mNumSources
OgreOggSoundRecord * mRecorder
bool mEFXSupport
LPALGENEFFECTS alGenEffects
LPALDELETEEFFECTS alDeleteEffects
LPALISEFFECT alIsEffect
LPALEFFECTI alEffecti
LPALEFFECTIV alEffectiv
LPALEFFECTF alEffectf
LPALEFFECTFV alEffectfv
LPALGETEFFECTI alGetEffecti
LPALGETEFFECTIV alGetEffectiv
LPALGETEFFECTF alGetEffectf
LPALGETEFFECTFV alGetEffectfv
LPALGENFILTERS alGenFilters
LPALDELETEFILTERS alDeleteFilters
LPALISFILTER alIsFilter
LPALFILTERI alFilteri
LPALFILTERIV alFilteriv
LPALFILTERF alFilterf
LPALFILTERFV alFilterfv
LPALGETFILTERI alGetFilteri
LPALGETFILTERIV alGetFilteriv
LPALGETFILTERF alGetFilterf
LPALGETFILTERFV alGetFilterfv
LPALGENAUXILIARYEFFECTSLOTS alGenAuxiliaryEffectSlots
LPALDELETEAUXILIARYEFFECTSLOTS alDeleteAuxiliaryEffectSlots
LPALISAUXILIARYEFFECTSLOT alIsAuxiliaryEffectSlot
LPALAUXILIARYEFFECTSLOTI alAuxiliaryEffectSloti
LPALAUXILIARYEFFECTSLOTIV alAuxiliaryEffectSlotiv
LPALAUXILIARYEFFECTSLOTF alAuxiliaryEffectSlotf
LPALAUXILIARYEFFECTSLOTFV alAuxiliaryEffectSlotfv
LPALGETAUXILIARYEFFECTSLOTI alGetAuxiliaryEffectSloti
LPALGETAUXILIARYEFFECTSLOTIV alGetAuxiliaryEffectSlotiv
LPALGETAUXILIARYEFFECTSLOTF alGetAuxiliaryEffectSlotf
LPALGETAUXILIARYEFFECTSLOTFV alGetAuxiliaryEffectSlotfv
LPEAXSETBUFFERMODE mEAXSetBufferMode
LPEAXGETBUFFERMODE mEAXGetBufferMode
bool mEAXSupport
int mEAXVersion
bool mXRamSupport
EffectList * mFilterList
EffectList * mEffectList
std::vector< ALuint > * mEffectSlotList
ALint mNumEffectSlots
ALint mNumSendsPerSource
ALenum mXRamSize
ALenum mXRamFree
ALenum mXRamAuto
ALenum mXRamHardware
ALenum mXRamAccessible
ALenum mCurrentXRamMode
ALint mXRamSizeMB
ALint mXRamFreeMB
OgreOggListener * mListener
Static Private Attributes
static OgreOggSoundManager * pInstance
Friends
class OgreOggSoundFactory
Detailed Description
Handles ALL sounds
Definition at line 81 of file OgreOggSoundManager.h.
Member Typedef Documentation
typedef ALboolean(__cdecl * OgreOggSound::OgreOggSoundManager::LPEAXSETBUFFERMODE)(ALsizei n, ALuint *buffers, ALint value) [private]
XRAM Support
typedef ALenum(__cdecl * OgreOggSound::OgreOggSoundManager::LPEAXGETBUFFERMODE)(ALuint buffer, ALint *value) [private]
Constructor & Destructor Documentation
OgreOggSound::OgreOggSoundManager::OgreOggSoundManager ()
Creates a manager for all sounds within the application.
OgreOggSound::OgreOggSoundManager::~OgreOggSoundManager ()
Destroys this manager.
Remarks:
Destroys all sound objects and thread if defined. Cleans up all OpenAL objects, buffers and devices and closes down the audio device.
Member Function Documentation
static OgreOggSoundManager& OgreOggSound::OgreOggSoundManager::getSingleton (void) [static]
Gets a singleton reference.
static OgreOggSoundManager* OgreOggSound::OgreOggSoundManager::getSingletonPtr (void) [static]
Gets a singleton reference.
bool OgreOggSound::OgreOggSoundManager::init (const std::string & deviceName = "")
Initialises the audio device.
Remarks:
Attempts to initialise the audio device for sound playback. Internally some logging is done to list features supported as well as creating a pool of sources from which sounds can be attached and played.
Parameters:
Audio device string to open, will use default device if not found.
int OgreOggSound::OgreOggSoundManager::createSourcePool ()
Creates a pool of OpenAL sources for playback.
Remarks:
Attempts to create a pool of source objects which allow simultaneous audio playback. The number of sources will be clamped to either the hardware maximum or [MAX_SOURCES] whichever comes first.
void OgreOggSound::OgreOggSoundManager::setMasterVolume (ALfloat vol)
Sets the global volume for all sounds
Parameters:
vol global attenuation for all sounds.
ALfloat OgreOggSound::OgreOggSoundManager::getMasterVolume ()
Gets the current global volume for all sounds
OgreOggISound* OgreOggSound::OgreOggSoundManager::createSound (const std::string & name, const std::string & file, bool stream = false, bool loop = false, bool preBuffer = false)
Creates a single sound object.
Remarks:
Creates and inits a single sound object, depending on passed parameters this function will create a static/streamed sound. Each sound must have a unique name within the manager.
Parameters:
name Unique name of sound
file Audio file path string
stream Flag indicating if the sound sound be streamed.
loop Flag indicating if the file should loop.
preBuffer Flag indicating if a source should be attached at creation.
OgreOggISound* OgreOggSound::OgreOggSoundManager::createSound (Ogre::SceneManager & scnMgr, const std::string & name, const std::string & file, bool stream = false, bool loop = false, bool preBuffer = false)
Creates a single sound object.
Remarks:
Plugin specific version of createSound, uses createMovableObject() to instantiate a sound automatically registered with the supplied SceneManager, allows OGRE to automatically cleanup/manage this sound. Each sound must have a unique name within the manager.
Parameters:
scnMgr SceneManager to use to create sound
name Unique name of sound
file Audio file path string
stream Flag indicating if the sound sound be streamed.
loop Flag indicating if the file should loop.
preBuffer Flag indicating if a source should be attached at creation.
OgreOggISound* OgreOggSound::OgreOggSoundManager::getSound (const std::string & name)
Gets a named sound.
Remarks:
Returns a named sound object if defined, NULL otherwise.
Parameters:
name Sound name.
Ogre::StringVector OgreOggSound::OgreOggSoundManager::getSoundList ()
Gets list of created sounds.
Remarks:
Returns a vector of sound name strings.
bool OgreOggSound::OgreOggSoundManager::hasSound (const std::string & name)
Returns whether named sound exists.
Remarks:
Checks sound map for a named sound.
Parameters:
name Sound name.
void OgreOggSound::OgreOggSoundManager::playSound (const Ogre::String & sName)
Plays a sound.
Remarks:
NOTE:- it is essential this function is used to play a sound when using BOOST Threads. Accessing a sound directly and calling its functions by-passes the thread mutex and causes audio artefacts and memory curruption. (Non multi-threaded does not have this problem.)
void OgreOggSound::OgreOggSoundManager::pauseSound (const Ogre::String & sName)
Pauses a sound.
Remarks:
NOTE:- it is essential this function is used to play a sound when using BOOST Threads. Accessing a sound directly and calling its functions by-passes the thread mutex and causes audio artefacts and memory curruption. (Non multi-threaded does not have this problem.)
void OgreOggSound::OgreOggSoundManager::stopSound (const Ogre::String & sName)
Stops a sound.
Remarks:
NOTE:- it is essential this function is used to play a sound when using BOOST Threads. Accessing a sound directly and calling its functions by-passes the thread mutex and causes audio artefacts and memory curruption. (Non multi-threaded does not have this problem.)
void OgreOggSound::OgreOggSoundManager::stopAllSounds ()
Stops all currently playing sounds.
void OgreOggSound::OgreOggSoundManager::pauseAllSounds ()
Pauses all currently playing sounds.
void OgreOggSound::OgreOggSoundManager::muteAllSounds ()
Mutes all sounds.
void OgreOggSound::OgreOggSoundManager::unmuteAllSounds ()
Un mutes all sounds.
void OgreOggSound::OgreOggSoundManager::resumeAllPausedSounds ()
Resumes all previously playing sounds.
void OgreOggSound::OgreOggSoundManager::destroyAllSounds ()
Destroys all sounds within manager.
Remarks:
Destroys all sound objects created by this manager.
bool OgreOggSound::OgreOggSoundManager::hasXRamSupport () [inline]
Returns XRAM support status.
Definition at line 228 of file OgreOggSoundManager.h.
bool OgreOggSound::OgreOggSoundManager::hasEFXSupport () [inline]
Returns EFX support status.
Definition at line 231 of file OgreOggSoundManager.h.
bool OgreOggSound::OgreOggSoundManager::hasEAXSupport () [inline]
Returns EAX support status.
Definition at line 234 of file OgreOggSoundManager.h.
void OgreOggSound::OgreOggSoundManager::destroySound (const std::string & name = "")
Destroys a single sound.
Remarks:
Destroys a single sound object.
Parameters:
name Sound name to destroy.
void OgreOggSound::OgreOggSoundManager::updateBuffers ()
Updates all sound buffers.
Remarks:
Iterates all sounds and updates their buffers.
Referenced by threadUpdate().
bool OgreOggSound::OgreOggSoundManager::requestSoundSource (OgreOggISound * sound = 0)
Requests a free source object.
Remarks:
Retrieves a free source object and attaches it to the specified sound object. Internally checks for any currently available sources, then checks stopped sounds and finally prioritised sounds.
Parameters:
sound Sound pointer.
bool OgreOggSound::OgreOggSoundManager::releaseSoundSource (OgreOggISound * sound = 0)
Release a sounds source.
Remarks:
Releases a specified sounds source object back to the system, allowing it to be re-used by another sound.
Parameters:
sound Sound pointer.
void OgreOggSound::OgreOggSoundManager::setDistanceModel (ALenum value)
Sets distance model.
Remarks:
Sets the global distance attenuation algorithm used by all sounds in the system.
Parameters:
value ALenum value of distance model.
void OgreOggSound::OgreOggSoundManager::setDopplerFactor (Ogre::Real factor = 1.f)
Sets doppler factor.
Remarks:
Sets the global doppler factor which affects attenuation for all sounds
Parameters:
factor Factor scale (>0).
void OgreOggSound::OgreOggSoundManager::setSpeedOfSound (Ogre::Real speed = 363.f)
Sets speed of sound.
Remarks:
Sets the global speed of sound used in the attenuation algorithm, affects all sounds.
Parameters:
speed Speed (m/s).
Ogre::StringVector OgreOggSound::OgreOggSoundManager::getDeviceList ()
Gets a list of device strings
Remarks:
Creates a list of available audio device strings
OgreOggListener* OgreOggSound::OgreOggSoundManager::getListener () [inline]
Returns pointer to listener.
Definition at line 296 of file OgreOggSoundManager.h.
int OgreOggSound::OgreOggSoundManager::getNumSources () [inline]
Returns number of sources created.
Definition at line 299 of file OgreOggSoundManager.h.
void OgreOggSound::OgreOggSoundManager::processQueuedSounds (void)
Opens all queued sounds.
Remarks:
To prevent calling thread blocking when using ov_open_callbacks() we offload this call onto the update thread. This function basically opens an ogg file for reading and notifys its parent sound that its ready to be used.
Referenced by threadUpdate().
void OgreOggSound::OgreOggSoundManager::update (Ogre::Real fTime = 0.f)
Updates system.
Remarks:
Iterates all sounds and updates them.
Parameters:
fTime Elapsed frametime.
void OgreOggSound::OgreOggSoundManager::setXRamBuffer (ALsizei numBuffers, ALuint * buffers)
Sets XRam buffers.
Remarks:
Currently defaults to AL_STORAGE_AUTO.
void OgreOggSound::OgreOggSoundManager::setXRamBufferMode (ALenum mode)
Sets XRam buffers storage mode.
Remarks:
Should be called before creating any sounds Options: AL_STORAGE_AUTOMATIC | AL_STORAGE_HARDWARE | AL_STORAGE_ACCESSIBLE
void OgreOggSound::OgreOggSoundManager::setEFXDistanceUnits (Ogre::Real unit = 3.3f)
Sets the distance units of measurement for EFX effects.
Remarks:
Parameters:
unit units(meters).
bool OgreOggSound::OgreOggSoundManager::createEFXFilter (const std::string & eName, ALint type, ALfloat gain = 1.0, ALfloat hfGain = 1.0)
Creates a specified EFX filter
Remarks:
Creates a specified EFX filter if hardware supports it.
Parameters:
eName name for filter.
type see OpenAL docs for available filters.
bool OgreOggSound::OgreOggSoundManager::createEFXEffect (const std::string & eName, ALint type, EAXREVERBPROPERTIES * props = 0)
Creates a specified EFX effect
Remarks:
Creates a specified EFX effect if hardware supports it. Optional reverb preset structure can be passed which will be applied to the effect. See eax-util.h for list of presets.
Parameters:
eName name for effect.
type see OpenAL docs for available effects.
props legacy structure describing a preset reverb effect.
bool OgreOggSound::OgreOggSoundManager::setEFXSoundProperties (const std::string & eName, Ogre::Real airAbsorption = 0.f, Ogre::Real roomRolloff = 0.f, Ogre::Real coneOuterHF = 0.f)
Sets extended properties on a specified sounds source
Remarks:
Tries to set EFX extended source properties.
Parameters:
sName name of sound.
airAbsorption absorption factor for air.
roomRolloff room rolloff factor.
coneOuterHF cone outer gain factor for High frequencies.
bool OgreOggSound::OgreOggSoundManager::setEFXEffectParameter (const std::string & eName, ALint effectType, ALenum attrib, ALfloat param)
Sets a specified paremeter on an effect
Remarks:
Tries to set a parameter value on a specified effect. Returns true/false.
Parameters:
eName name of effect.
effectType see OpenAL docs for available effects.
attrib parameter value to alter.
param float value to set.
bool OgreOggSound::OgreOggSoundManager::setEFXEffectParameter (const std::string & eName, ALint type, ALenum attrib, ALfloat * params = 0)
Sets a specified paremeter on an effect
Remarks:
Tries to set a parameter value on a specified effect. Returns true/false.
Parameters:
eName name of effect.
effectType see OpenAL docs for available effects.
attrib parameter value to alter.
param vector pointer of float values to set.
bool OgreOggSound::OgreOggSoundManager::setEFXEffectParameter (const std::string & eName, ALint type, ALenum attrib, ALint param)
Sets a specified paremeter on an effect
Remarks:
Tries to set a parameter value on a specified effect. Returns true/false.
Parameters:
eName name of effect.
effectType see OpenAL docs for available effects.
attrib parameter value to alter.
param integer value to set.
bool OgreOggSound::OgreOggSoundManager::setEFXEffectParameter (const std::string & eName, ALint type, ALenum attrib, ALint * params = 0)
Sets a specified paremeter on an effect
Remarks:
Tries to set a parameter value on a specified effect. Returns true/false.
Parameters:
eName name of effect.
effectType see OpenAL docs for available effects.
attrib parameter value to alter.
params vector pointer of integer values to set.
int OgreOggSound::OgreOggSoundManager::getNumberOfSupportedEffectSlots ()
Gets the maximum number of Auxiliary Effect slots per source
Remarks:
Determines how many simultaneous effects can be applied to any one source object
int OgreOggSound::OgreOggSoundManager::getNumberOfCreatedEffectSlots ()
Gets the number of currently created Auxiliary Effect slots
Remarks:
Returns number of slots craeted and available for effects/filters.
bool OgreOggSound::OgreOggSoundManager::createEFXSlot ()
Creates a specified EFX filter
Remarks:
Creates a specified EFX filter if hardware supports it.
Parameters:
eName name for filter. type see OpenAL docs for available filter types.
bool OgreOggSound::OgreOggSoundManager::attachEffectToSound (const std::string & sName, ALuint slot, const Ogre::String & effect = "", const Ogre::String & filter = "")
Attaches an effect to a sound
Remarks:
Currently sound must have a source attached prior to this call.
Parameters:
sName name of sound
slot slot ID
effect name of effect as defined when created
filter name of filter as defined when created
bool OgreOggSound::OgreOggSoundManager::attachFilterToSound (const std::string & sName, const Ogre::String & filter = "")
Attaches a filter to a sound
Remarks:
Currently sound must have a source attached prior to this call.
Parameters:
sName name of sound
filter name of filter as defined when created
bool OgreOggSound::OgreOggSoundManager::detachEffectFromSound (const std::string & sName, ALuint slotID)
Detaches all effects from a sound
Remarks:
Currently sound must have a source attached prior to this call.
Parameters:
sName name of sound
slot slot ID
bool OgreOggSound::OgreOggSoundManager::detachFilterFromSound (const std::string & sName)
Detaches all filters from a sound
Remarks:
Currently sound must have a source attached prior to this call.
Parameters:
sName name of sound
bool OgreOggSound::OgreOggSoundManager::isEffectSupported (ALint effectID)
Returns whether a specified effect is supported
Parameters:
effectID OpenAL effect/filter id. (AL_EFFECT... | AL_FILTER...)
OgreOggSoundRecord* OgreOggSound::OgreOggSoundManager::getRecorder () [inline]
Gets recording device
Definition at line 483 of file OgreOggSoundManager.h.
bool OgreOggSound::OgreOggSoundManager::isRecordingAvailable ()
Returns whether a capture device is available
OgreOggSoundRecord* OgreOggSound::OgreOggSoundManager::createRecorder ()
Creates a recordable object
bool OgreOggSound::OgreOggSoundManager::releaseSharedBuffer (const Ogre::String & sName, ALuint & buffer)
Releases a shared audio buffer
Remarks:
Each shared audio buffer is reference counted so destruction is handled correctly, this function merely decrements the reference count, only destroying when no sounds are referencing buffer.
Parameters:
sName Name of audio file
bool OgreOggSound::OgreOggSoundManager::registerSharedBuffer (const Ogre::String & sName, ALuint & buffer)
Registers a shared audio buffer
Remarks:
Its possible to share audio buffer data among many sources so this function registers an audio buffer as 'sharable', meaning if a the same audio file is created more then once, it will simply use the original buffer data instead of creating/loading the same data again.
Parameters:
sName Name of audio file
buffer OpenAL buffer ID holding audio data
void OgreOggSound::OgreOggSoundManager::queueDelayedSound (OgreOggISound * sound = 0, DELAYED_ACTION action = DA_PLAY)
Queues a sound to play
Remarks:
Synchronisation function for Threaded version of library, fixes the bug where creating and immediately playing a sound through OgreOggISound::play() results in no sound. This is because theres no facilty to re-check a play delayed sound after it has been opened. This function therefore adds the specified sound to an internal list which is checked in update() and an attempt is made to play() the sound. NOTE (Multithreaded version ONLY):- calling OgreOggISound::play()/stop()/pause() directly still has the potential to crash out as these functions are not mutex locked. If Threading is enabled you SHOULD use the OgreOggSoundManager::playSound()/pauseSound()/stopSound() functions. This will be addressed in the near future.
static void OgreOggSound::OgreOggSoundManager::threadUpdate () [inline, static]
Threaded function for streaming updates
Remarks:
Optional threading function specified in OgreOggPreReqs.h. Implemented to handle updating of streamed audio buffers independently of main game thread, unthreaded streaming would be disrupted by any pauses or large frame lags, due to the fact that OpenAL itself runs in its own thread. If the audio buffers aren't constantly re-filled the sound will be automatically stopped by OpenAL. Static sounds do not suffer this problem because all the audio data is preloaded into memory.
Definition at line 544 of file OgreOggSoundManager.h.
References OgreOggSoundManager::getSingleton(), processQueuedSounds(), and updateBuffers().
void OgreOggSound::OgreOggSoundManager::_destroySound (OgreOggISound * sound = 0) [protected]
Destroys a single sound.
Remarks:
Destroys a single sound object.
Parameters:
sound Sound to destroy.
void OgreOggSound::OgreOggSoundManager::_removeFromLists (OgreOggISound * sound = 0) [protected]
Removes references of a sound from all possible internal lists.
Remarks:
Various lists exist to manage numerous states of a sound, this function exists to remove a sound object from any/all lists it has previously been added to.
Parameters:
sound Sound to destroy.
ALuint OgreOggSound::OgreOggSoundManager::_getSharedBuffer (const Ogre::String & sName) [private]
Gets a shared audio buffer
Remarks:
Returns a previously loaded shared buffer reference if available. NOTE:- Increments a reference count so releaseSharedBuffer() must be called when buffer is no longer used.
Parameters:
sName Name of audio file
void OgreOggSound::OgreOggSoundManager::_release () [private]
Releases all sounds and buffers
Remarks:
Release all sounds and their associated OpenAL objects from the system.
void OgreOggSound::OgreOggSoundManager::_checkFeatureSupport () [private]
Checks and Logs a supported feature list
Remarks:
Queries OpenAL for various supported features and lists them with the LogManager.
bool OgreOggSound::OgreOggSoundManager::_checkEFXSupport () [private]
Checks for EFX hardware support
bool OgreOggSound::OgreOggSoundManager::_checkXRAMSupport () [private]
Checks for XRAM hardware support
void OgreOggSound::OgreOggSoundManager::_determineAuxEffectSlots () [private]
Checks for EAX effect support
ALuint OgreOggSound::OgreOggSoundManager::_getEFXFilter (const std::string & fName) [private]
Gets a specified EFX filter
Parameters:
fName name of filter as defined when created.
ALuint OgreOggSound::OgreOggSoundManager::_getEFXEffect (const std::string & eName) [private]
Gets a specified EFX Effect
Parameters:
eName name of effect as defined when created.
ALuint OgreOggSound::OgreOggSoundManager::_getEFXSlot (int slotID = 0) [private]
Gets a specified EFX Effect slot
Parameters:
slotID index of auxiliary effect slot
bool OgreOggSound::OgreOggSoundManager::_setEAXReverbProperties (EFXEAXREVERBPROPERTIES * pEFXEAXReverb, ALuint uiEffect) [private]
Sets EAX reverb properties using a specified present
Parameters:
pEFXEAXReverb pointer to converted EFXEAXREVERBPROPERTIES structure object
uiEffect effect ID
bool OgreOggSound::OgreOggSoundManager::_attachEffectToSlot (ALuint slot, ALuint effect) [private]
Attaches a created effect to an Auxiliary slot
Parameters:
slot slot ID
effect effect ID
void OgreOggSound::OgreOggSoundManager::_reactivateQueuedSounds () [private]
Re-activates any sounds which had their source stolen.
Remarks:
When all sources are in use the sounds begin to give up their source objects to higher priority sounds. When this happens the lower priority sound is queued ready to re-play when a source becomes available again, this function checks this queue and tries to re-play those sounds. Only affects sounds which were originally playing when forced to give up their source object.
void OgreOggSound::OgreOggSoundManager::_enumDevices () [private]
Enumerates audio devices.
Remarks:
Gets a list of audio device available.
Friends And Related Function Documentation
friend class OgreOggSoundFactory [friend]
Definition at line 769 of file OgreOggSoundManager.h.
Member Data Documentation
boost::recursive_mutex OgreOggSound::OgreOggSoundManager::mMutex
Definition at line 528 of file OgreOggSoundManager.h.
static::boost::thread* OgreOggSound::OgreOggSoundManager::mUpdateThread
Definition at line 530 of file OgreOggSoundManager.h.
bool OgreOggSound::OgreOggSoundManager::mShuttingDown [static]
Definition at line 531 of file OgreOggSoundManager.h.
ALCdevice* OgreOggSound::OgreOggSoundManager::mDevice [private]
OpenAL device objects
Definition at line 658 of file OgreOggSoundManager.h.
ALCcontext* OgreOggSound::OgreOggSoundManager::mContext [private]
Definition at line 659 of file OgreOggSoundManager.h.
ALfloat OgreOggSound::OgreOggSoundManager::mOrigVolume [private]
Definition at line 661 of file OgreOggSoundManager.h.
SoundMap OgreOggSound::OgreOggSoundManager::mSoundMap [private]
Sound lists
Definition at line 665 of file OgreOggSoundManager.h.
ActiveList OgreOggSound::OgreOggSoundManager::mActiveSounds [private]
Definition at line 666 of file OgreOggSoundManager.h.
FileOpenList OgreOggSound::OgreOggSoundManager::mQueuedSounds [private]
Definition at line 667 of file OgreOggSoundManager.h.
ActiveList OgreOggSound::OgreOggSoundManager::mPlayQueue [private]
Definition at line 668 of file OgreOggSoundManager.h.
ActiveList OgreOggSound::OgreOggSoundManager::mPauseQueue [private]
Definition at line 669 of file OgreOggSoundManager.h.
ActiveList OgreOggSound::OgreOggSoundManager::mStopQueue [private]
Definition at line 670 of file OgreOggSoundManager.h.
ActiveList OgreOggSound::OgreOggSoundManager::mPausedSounds [private]
Definition at line 671 of file OgreOggSoundManager.h.
ActiveList OgreOggSound::OgreOggSoundManager::mSoundsToReactivate [private]
Definition at line 672 of file OgreOggSoundManager.h.
SourceList OgreOggSound::OgreOggSoundManager::mSourcePool [private]
Definition at line 673 of file OgreOggSoundManager.h.
FeatureList OgreOggSound::OgreOggSoundManager::mEFXSupportList [private]
Definition at line 674 of file OgreOggSoundManager.h.
SharedBufferList OgreOggSound::OgreOggSoundManager::mSharedBuffers [private]
Definition at line 675 of file OgreOggSoundManager.h.
OgreOggSoundManager* OgreOggSound::OgreOggSoundManager::pInstance [static, private]
Manager instance
Definition at line 679 of file OgreOggSoundManager.h.
ALCchar* OgreOggSound::OgreOggSoundManager::mDeviceStrings [private]
Definition at line 680 of file OgreOggSoundManager.h.
int OgreOggSound::OgreOggSoundManager::mNumSources [private]
Definition at line 681 of file OgreOggSoundManager.h.
OgreOggSoundRecord* OgreOggSound::OgreOggSoundManager::mRecorder [private]
Definition at line 683 of file OgreOggSoundManager.h.
bool OgreOggSound::OgreOggSoundManager::mEFXSupport [private]
EFX Support
Definition at line 688 of file OgreOggSoundManager.h.
LPALGENEFFECTS OgreOggSound::OgreOggSoundManager::alGenEffects [private]
Definition at line 695 of file OgreOggSoundManager.h.
LPALDELETEEFFECTS OgreOggSound::OgreOggSoundManager::alDeleteEffects [private]
Definition at line 696 of file OgreOggSoundManager.h.
LPALISEFFECT OgreOggSound::OgreOggSoundManager::alIsEffect [private]
Definition at line 697 of file OgreOggSoundManager.h.
LPALEFFECTI OgreOggSound::OgreOggSoundManager::alEffecti [private]
Definition at line 698 of file OgreOggSoundManager.h.
LPALEFFECTIV OgreOggSound::OgreOggSoundManager::alEffectiv [private]
Definition at line 699 of file OgreOggSoundManager.h.
LPALEFFECTF OgreOggSound::OgreOggSoundManager::alEffectf [private]
Definition at line 700 of file OgreOggSoundManager.h.
LPALEFFECTFV OgreOggSound::OgreOggSoundManager::alEffectfv [private]
Definition at line 701 of file OgreOggSoundManager.h.
LPALGETEFFECTI OgreOggSound::OgreOggSoundManager::alGetEffecti [private]
Definition at line 702 of file OgreOggSoundManager.h.
LPALGETEFFECTIV OgreOggSound::OgreOggSoundManager::alGetEffectiv [private]
Definition at line 703 of file OgreOggSoundManager.h.
LPALGETEFFECTF OgreOggSound::OgreOggSoundManager::alGetEffectf [private]
Definition at line 704 of file OgreOggSoundManager.h.
LPALGETEFFECTFV OgreOggSound::OgreOggSoundManager::alGetEffectfv [private]
Definition at line 705 of file OgreOggSoundManager.h.
LPALGENFILTERS OgreOggSound::OgreOggSoundManager::alGenFilters [private]
Definition at line 708 of file OgreOggSoundManager.h.
LPALDELETEFILTERS OgreOggSound::OgreOggSoundManager::alDeleteFilters [private]
Definition at line 709 of file OgreOggSoundManager.h.
LPALISFILTER OgreOggSound::OgreOggSoundManager::alIsFilter [private]
Definition at line 710 of file OgreOggSoundManager.h.
LPALFILTERI OgreOggSound::OgreOggSoundManager::alFilteri [private]
Definition at line 711 of file OgreOggSoundManager.h.
LPALFILTERIV OgreOggSound::OgreOggSoundManager::alFilteriv [private]
Definition at line 712 of file OgreOggSoundManager.h.
LPALFILTERF OgreOggSound::OgreOggSoundManager::alFilterf [private]
Definition at line 713 of file OgreOggSoundManager.h.
LPALFILTERFV OgreOggSound::OgreOggSoundManager::alFilterfv [private]
Definition at line 714 of file OgreOggSoundManager.h.
LPALGETFILTERI OgreOggSound::OgreOggSoundManager::alGetFilteri [private]
Definition at line 715 of file OgreOggSoundManager.h.
LPALGETFILTERIV OgreOggSound::OgreOggSoundManager::alGetFilteriv [private]
Definition at line 716 of file OgreOggSoundManager.h.
LPALGETFILTERF OgreOggSound::OgreOggSoundManager::alGetFilterf [private]
Definition at line 717 of file OgreOggSoundManager.h.
LPALGETFILTERFV OgreOggSound::OgreOggSoundManager::alGetFilterfv [private]
Definition at line 718 of file OgreOggSoundManager.h.
LPALGENAUXILIARYEFFECTSLOTS OgreOggSound::OgreOggSoundManager::alGenAuxiliaryEffectSlots [private]
Definition at line 721 of file OgreOggSoundManager.h.
LPALDELETEAUXILIARYEFFECTSLOTS OgreOggSound::OgreOggSoundManager::alDeleteAuxiliaryEffectSlots [private]
Definition at line 722 of file OgreOggSoundManager.h.
LPALISAUXILIARYEFFECTSLOT OgreOggSound::OgreOggSoundManager::alIsAuxiliaryEffectSlot [private]
Definition at line 723 of file OgreOggSoundManager.h.
LPALAUXILIARYEFFECTSLOTI OgreOggSound::OgreOggSoundManager::alAuxiliaryEffectSloti [private]
Definition at line 724 of file OgreOggSoundManager.h.
LPALAUXILIARYEFFECTSLOTIV OgreOggSound::OgreOggSoundManager::alAuxiliaryEffectSlotiv [private]
Definition at line 725 of file OgreOggSoundManager.h.
LPALAUXILIARYEFFECTSLOTF OgreOggSound::OgreOggSoundManager::alAuxiliaryEffectSlotf [private]
Definition at line 726 of file OgreOggSoundManager.h.
LPALAUXILIARYEFFECTSLOTFV OgreOggSound::OgreOggSoundManager::alAuxiliaryEffectSlotfv [private]
Definition at line 727 of file OgreOggSoundManager.h.
LPALGETAUXILIARYEFFECTSLOTI OgreOggSound::OgreOggSoundManager::alGetAuxiliaryEffectSloti [private]
Definition at line 728 of file OgreOggSoundManager.h.
LPALGETAUXILIARYEFFECTSLOTIV OgreOggSound::OgreOggSoundManager::alGetAuxiliaryEffectSlotiv [private]
Definition at line 729 of file OgreOggSoundManager.h.
LPALGETAUXILIARYEFFECTSLOTF OgreOggSound::OgreOggSoundManager::alGetAuxiliaryEffectSlotf [private]
Definition at line 730 of file OgreOggSoundManager.h.
LPALGETAUXILIARYEFFECTSLOTFV OgreOggSound::OgreOggSoundManager::alGetAuxiliaryEffectSlotfv [private]
Definition at line 731 of file OgreOggSoundManager.h.
LPEAXSETBUFFERMODE OgreOggSound::OgreOggSoundManager::mEAXSetBufferMode [private]
Definition at line 738 of file OgreOggSoundManager.h.
LPEAXGETBUFFERMODE OgreOggSound::OgreOggSoundManager::mEAXGetBufferMode [private]
Definition at line 739 of file OgreOggSoundManager.h.
bool OgreOggSound::OgreOggSoundManager::mEAXSupport [private]
EAX Support
Definition at line 743 of file OgreOggSoundManager.h.
int OgreOggSound::OgreOggSoundManager::mEAXVersion [private]
Definition at line 744 of file OgreOggSoundManager.h.
bool OgreOggSound::OgreOggSoundManager::mXRamSupport [private]
Definition at line 746 of file OgreOggSoundManager.h.
EffectList* OgreOggSound::OgreOggSoundManager::mFilterList [private]
Definition at line 748 of file OgreOggSoundManager.h.
EffectList* OgreOggSound::OgreOggSoundManager::mEffectList [private]
Definition at line 749 of file OgreOggSoundManager.h.
std::vector<ALuint>* OgreOggSound::OgreOggSoundManager::mEffectSlotList [private]
Definition at line 750 of file OgreOggSoundManager.h.
ALint OgreOggSound::OgreOggSoundManager::mNumEffectSlots [private]
Definition at line 752 of file OgreOggSoundManager.h.
ALint OgreOggSound::OgreOggSoundManager::mNumSendsPerSource [private]
Definition at line 753 of file OgreOggSoundManager.h.
ALenum OgreOggSound::OgreOggSoundManager::mXRamSize [private]
Definition at line 755 of file OgreOggSoundManager.h.
ALenum OgreOggSound::OgreOggSoundManager::mXRamFree [private]
Definition at line 755 of file OgreOggSoundManager.h.
ALenum OgreOggSound::OgreOggSoundManager::mXRamAuto [private]
Definition at line 755 of file OgreOggSoundManager.h.
ALenum OgreOggSound::OgreOggSoundManager::mXRamHardware [private]
Definition at line 755 of file OgreOggSoundManager.h.
ALenum OgreOggSound::OgreOggSoundManager::mXRamAccessible [private]
Definition at line 755 of file OgreOggSoundManager.h.
ALenum OgreOggSound::OgreOggSoundManager::mCurrentXRamMode [private]
Definition at line 755 of file OgreOggSoundManager.h.
ALint OgreOggSound::OgreOggSoundManager::mXRamSizeMB [private]
Definition at line 762 of file OgreOggSoundManager.h.
ALint OgreOggSound::OgreOggSoundManager::mXRamFreeMB [private]
Definition at line 762 of file OgreOggSoundManager.h.
OgreOggListener* OgreOggSound::OgreOggSoundManager::mListener [private]
Listener pointer
Definition at line 767 of file OgreOggSoundManager.h.
The documentation for this class was generated from the following file:
C:/Current Projects/Audio Library/ogreoggsound/include/OgreOggSoundManager.h